# Generated by Django 5.2.17 on 2026-09-25 02:02

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCliente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cliente",
                "verbose_name_plural": "historical clientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPeriodo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ],
                        verbose_name="mes",
                    ),
                ),
                (
                    "modo_asignacion",
                    models.CharField(
                        choices=[
                            ("AUTO", "Automático (por Ventas)"),
                            ("MANUAL", "Manual"),
                        ],
                        default="AUTO",
                        help_text="Automático: cada servicio recibe según su participación en las Ventas del mes. Manual: se usan los % cargados abajo (deben sumar 100%).",
                        max_length=10,
                        verbose_name="% de asignación de costos fijos",
                    ),
                ),
                (
                    "cerrado",
                    models.BooleanField(
                        default=False,
                        help_text="Un mes cerrado ya no se puede modificar, salvo por un Administrador.",
                        verbose_name="mes cerrado",
                    ),
                ),
                (
                    "saldo_proveedores",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dato informativo (memo del Estado de Resultados). No forma parte del resultado.",
                        max_digits=16,
                        null=True,
                        verbose_name="saldo de proveedores al cierre del mes",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical período (mes)",
                "verbose_name_plural": "historical períodos (meses)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPersona",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                (
                    "apellido_nombre",
                    models.CharField(max_length=200, verbose_name="apellido y nombre"),
                ),
                (
                    "cuil",
                    models.CharField(
                        blank=True,
                        help_text="11 dígitos sin guiones. Puede quedar vacío para terceros que facturan (ej. choferes).",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIL",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar cuando la persona se da de baja.",
                        verbose_name="activa",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical persona",
                "verbose_name_plural": "historical personas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProveedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proveedor",
                "verbose_name_plural": "historical proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ],
                        verbose_name="mes",
                    ),
                ),
                (
                    "modo_asignacion",
                    models.CharField(
                        choices=[
                            ("AUTO", "Automático (por Ventas)"),
                            ("MANUAL", "Manual"),
                        ],
                        default="AUTO",
                        help_text="Automático: cada servicio recibe según su participación en las Ventas del mes. Manual: se usan los % cargados abajo (deben sumar 100%).",
                        max_length=10,
                        verbose_name="% de asignación de costos fijos",
                    ),
                ),
                (
                    "cerrado",
                    models.BooleanField(
                        default=False,
                        help_text="Un mes cerrado ya no se puede modificar, salvo por un Administrador.",
                        verbose_name="mes cerrado",
                    ),
                ),
                (
                    "saldo_proveedores",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dato informativo (memo del Estado de Resultados). No forma parte del resultado.",
                        max_digits=16,
                        null=True,
                        verbose_name="saldo de proveedores al cierre del mes",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "período (mes)",
                "verbose_name_plural": "períodos (meses)",
                "ordering": ["-anio", "-mes"],
                "permissions": [("ver_reportes", "Puede ver los reportes calculados")],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVenta",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_comprobante",
                    models.CharField(
                        help_text='Ej.: "Factura A", "Nota de Crédito A".',
                        max_length=60,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(verbose_name="punto de venta"),
                ),
                (
                    "numero",
                    models.PositiveBigIntegerField(verbose_name="N° de factura"),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Las notas de crédito se cargan en negativo.",
                        max_digits=16,
                        verbose_name="monto",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical factura de venta",
                "verbose_name_plural": "historical registro de ventas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGastoManual",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                (
                    "rubro",
                    models.CharField(
                        choices=[
                            ("ALQUILERES", "Alquileres"),
                            ("SERVICIOS", "Servicios (luz, gas, internet, etc.)"),
                            ("SEGUROS", "Seguros"),
                            ("IMPUESTOS", "Impuestos y Tasas"),
                            ("OTROS_GO", "Otros Gastos Operativos"),
                            ("LEASING", "Leasing Vehículos/Equipos"),
                            ("PLANES_PAGO", "Cuotas Planes de Pago"),
                            ("COMISIONES", "Comisiones Bancarias"),
                            ("INTERESES", "Intereses por Financiación"),
                            (
                                "LEY_25413",
                                "Impuesto a los Créditos y Débitos (Ley 25.413)",
                            ),
                            ("OTROS_INGRESOS", "Otros Ingresos"),
                            ("OTROS_EGRESOS_NO", "Otros Egresos (no operativos)"),
                            ("GANANCIAS", "Impuesto a las Ganancias (estimado)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text='Descripción del ítem, ej.: "Banco Provincia cta 1 (cuota + seguro + patente)".',
                        max_length=200,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="monto"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gasto cargado a mano",
                "verbose_name_plural": "historical apertura de gastos (carga manual)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAsignacionManual",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="% manual",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical % manual de asignación",
                "verbose_name_plural": "historical % manuales de asignación (sólo si el modo es Manual)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GastoManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                (
                    "rubro",
                    models.CharField(
                        choices=[
                            ("ALQUILERES", "Alquileres"),
                            ("SERVICIOS", "Servicios (luz, gas, internet, etc.)"),
                            ("SEGUROS", "Seguros"),
                            ("IMPUESTOS", "Impuestos y Tasas"),
                            ("OTROS_GO", "Otros Gastos Operativos"),
                            ("LEASING", "Leasing Vehículos/Equipos"),
                            ("PLANES_PAGO", "Cuotas Planes de Pago"),
                            ("COMISIONES", "Comisiones Bancarias"),
                            ("INTERESES", "Intereses por Financiación"),
                            (
                                "LEY_25413",
                                "Impuesto a los Créditos y Débitos (Ley 25.413)",
                            ),
                            ("OTROS_INGRESOS", "Otros Ingresos"),
                            ("OTROS_EGRESOS_NO", "Otros Egresos (no operativos)"),
                            ("GANANCIAS", "Impuesto a las Ganancias (estimado)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text='Descripción del ítem, ej.: "Banco Provincia cta 1 (cuota + seguro + patente)".',
                        max_length=200,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="monto"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_manuales",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
            ],
            options={
                "verbose_name": "gasto cargado a mano",
                "verbose_name_plural": "apertura de gastos (carga manual)",
                "ordering": ["-periodo__anio", "-periodo__mes", "rubro", "concepto"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="% manual",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_manuales",
                        to="gestion.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "% manual de asignación",
                "verbose_name_plural": "% manuales de asignación (sólo si el modo es Manual)",
                "ordering": ["periodo", "id"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                (
                    "apellido_nombre",
                    models.CharField(max_length=200, verbose_name="apellido y nombre"),
                ),
                (
                    "cuil",
                    models.CharField(
                        blank=True,
                        help_text="11 dígitos sin guiones. Puede quedar vacío para terceros que facturan (ej. choferes).",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIL",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar cuando la persona se da de baja.",
                        verbose_name="activa",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
                "ordering": ["apellido_nombre"],
            },
        ),
        migrations.CreateModel(
            name="LiquidacionNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                (
                    "mano_obra_directa",
                    models.BooleanField(
                        default=True,
                        help_text='"No" = estructura de Administración.',
                        verbose_name="¿mano de obra directa?",
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                            (
                                "POOL",
                                "Pool Operativo (Hidrolavadoras+Módulos+Climatización+Obras Civiles+Mant. Edilicios+Metalúrgica+Aluvión-Vista)",
                            ),
                            ("ADMIN", "Administración (estructura general)"),
                        ],
                        max_length=20,
                        verbose_name="servicio asignado",
                    ),
                ),
                (
                    "porcentaje_afectacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Entre 0 y 100. Si la persona se reparte entre dos servicios, cargá un renglón por cada uno.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="% de afectación a ese servicio",
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        blank=True,
                        help_text='Informativo. Ej.: "Petroleros Privados", "UOCRA", "Socio de la empresa".',
                        max_length=200,
                        verbose_name="régimen / vínculo",
                    ),
                ),
                (
                    "haberes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="haberes (neto de recibo)",
                    ),
                ),
                (
                    "contribuciones_patronales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="contribuciones patronales",
                    ),
                ),
                (
                    "sindicato_mutual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Importe final ya calculado por quien carga (según recibo y planilla del sindicato).",
                        max_digits=16,
                        verbose_name="sindicato y mutual",
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="honorarios (monotributistas)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nomina",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "renglón de nómina",
                "verbose_name_plural": "personal y nómina",
                "ordering": [
                    "-periodo__anio",
                    "-periodo__mes",
                    "persona__apellido_nombre",
                    "asignacion",
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionNomina",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                (
                    "mano_obra_directa",
                    models.BooleanField(
                        default=True,
                        help_text='"No" = estructura de Administración.',
                        verbose_name="¿mano de obra directa?",
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                            (
                                "POOL",
                                "Pool Operativo (Hidrolavadoras+Módulos+Climatización+Obras Civiles+Mant. Edilicios+Metalúrgica+Aluvión-Vista)",
                            ),
                            ("ADMIN", "Administración (estructura general)"),
                        ],
                        max_length=20,
                        verbose_name="servicio asignado",
                    ),
                ),
                (
                    "porcentaje_afectacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Entre 0 y 100. Si la persona se reparte entre dos servicios, cargá un renglón por cada uno.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="% de afectación a ese servicio",
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        blank=True,
                        help_text='Informativo. Ej.: "Petroleros Privados", "UOCRA", "Socio de la empresa".',
                        max_length=200,
                        verbose_name="régimen / vínculo",
                    ),
                ),
                (
                    "haberes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="haberes (neto de recibo)",
                    ),
                ),
                (
                    "contribuciones_patronales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="contribuciones patronales",
                    ),
                ),
                (
                    "sindicato_mutual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Importe final ya calculado por quien carga (según recibo y planilla del sindicato).",
                        max_digits=16,
                        verbose_name="sindicato y mutual",
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        verbose_name="honorarios (monotributistas)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical renglón de nómina",
                "verbose_name_plural": "historical personal y nómina",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$",
                                "El CUIL/CUIT debe tener 11 dígitos, sin guiones.",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCompra",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="cargado el"
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modificado el"
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_comprobante",
                    models.CharField(
                        help_text='Ej.: "Factura A", "Factura B", "Nota de Crédito A".',
                        max_length=60,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(verbose_name="punto de venta"),
                ),
                (
                    "numero",
                    models.PositiveBigIntegerField(verbose_name="N° de factura"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MATERIALES", "Materiales e Insumos"),
                            ("COMBUSTIBLE", "Combustible"),
                            ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                            ("OTROS_DIRECTOS", "Otros Costos Directos"),
                            (
                                "OTROS_EGRESOS",
                                "Otros Egresos (no corresponde a Costos por Servicio)",
                            ),
                        ],
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "servicio_asignado",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                            ("GENERAL", "GENERAL (a prorratear por ventas)"),
                            ("NA", "N/A — Otros Egresos (no aplica)"),
                        ],
                        max_length=20,
                        verbose_name="servicio asignado",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Las notas de crédito se cargan en negativo.",
                        max_digits=16,
                        verbose_name="monto",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical factura de compra",
                "verbose_name_plural": "historical registro de compras",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_comprobante",
                    models.CharField(
                        help_text='Ej.: "Factura A", "Factura B", "Nota de Crédito A".',
                        max_length=60,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(verbose_name="punto de venta"),
                ),
                (
                    "numero",
                    models.PositiveBigIntegerField(verbose_name="N° de factura"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MATERIALES", "Materiales e Insumos"),
                            ("COMBUSTIBLE", "Combustible"),
                            ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                            ("OTROS_DIRECTOS", "Otros Costos Directos"),
                            (
                                "OTROS_EGRESOS",
                                "Otros Egresos (no corresponde a Costos por Servicio)",
                            ),
                        ],
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "servicio_asignado",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                            ("GENERAL", "GENERAL (a prorratear por ventas)"),
                            ("NA", "N/A — Otros Egresos (no aplica)"),
                        ],
                        max_length=20,
                        verbose_name="servicio asignado",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Las notas de crédito se cargan en negativo.",
                        max_digits=16,
                        verbose_name="monto",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="gestion.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura de compra",
                "verbose_name_plural": "registro de compras",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado el"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="modificado el"),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_comprobante",
                    models.CharField(
                        help_text='Ej.: "Factura A", "Nota de Crédito A".',
                        max_length=60,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(verbose_name="punto de venta"),
                ),
                (
                    "numero",
                    models.PositiveBigIntegerField(verbose_name="N° de factura"),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("HIDRO", "Hidrolavadoras Industriales"),
                            ("MODULOS", "Módulos Transportables / Trailers"),
                            ("CLIMA", "Climatización"),
                            ("OBRAS", "Obras Civiles Menores"),
                            ("MANT_EDIL", "Mantenimiento Edilicios"),
                            ("PAE", "Soporte a Producción PAE"),
                            ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                            ("CERCOS", "Cercos Perimetrales y Corralitos"),
                            ("METAL", "Metalúrgica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Las notas de crédito se cargan en negativo.",
                        max_digits=16,
                        verbose_name="monto",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="gestion.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cargado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="gestion.periodo",
                        verbose_name="mes",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura de venta",
                "verbose_name_plural": "registro de ventas",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="periodo",
            constraint=models.UniqueConstraint(
                fields=("anio", "mes"), name="periodo_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="asignacionmanual",
            constraint=models.UniqueConstraint(
                fields=("periodo", "servicio"), name="asignacion_manual_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cuil", ""), _negated=True),
                fields=("cuil",),
                name="cuil_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidacionnomina",
            constraint=models.UniqueConstraint(
                fields=("persona", "periodo", "asignacion"), name="nomina_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.UniqueConstraint(
                fields=("proveedor", "tipo_comprobante", "punto_venta", "numero"),
                name="compra_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.UniqueConstraint(
                fields=("tipo_comprobante", "punto_venta", "numero"), name="venta_unica"
            ),
        ),
    ]
