# Generated by Django 5.2.17 on 2026-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_ayuda_epp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="servicio_asignado",
            field=models.CharField(
                choices=[
                    ("HIDRO", "Hidrolavadoras Industriales"),
                    ("MODULOS", "Módulos Transportables / Trailers"),
                    ("CLIMA", "Climatización"),
                    ("OBRAS", "Obras Civiles Menores"),
                    ("MANT_EDIL", "Mantenimiento Edilicios"),
                    ("PAE", "Soporte a Producción PAE"),
                    ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                    ("CERCOS", "Cercos Perimetrales y Corralitos"),
                    ("METAL", "Metalúrgica"),
                    ("GENERAL", "GENERAL (a prorratear por ventas)"),
                    (
                        "PERSONAL",
                        "GENERAL (a prorratear por personal afectado) — ej. EPP",
                    ),
                    ("NA", "N/A — Otros Egresos (no aplica)"),
                ],
                help_text='Si la factura es de varios servicios, elegí "GENERAL (a prorratear por ventas)". Si es de EPP (mamelucos, calzado, etc.), elegí "GENERAL (a prorratear por personal afectado)": se reparte según la cantidad de personal de cada servicio en el mes.',
                max_length=20,
                verbose_name="servicio asignado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompra",
            name="servicio_asignado",
            field=models.CharField(
                choices=[
                    ("HIDRO", "Hidrolavadoras Industriales"),
                    ("MODULOS", "Módulos Transportables / Trailers"),
                    ("CLIMA", "Climatización"),
                    ("OBRAS", "Obras Civiles Menores"),
                    ("MANT_EDIL", "Mantenimiento Edilicios"),
                    ("PAE", "Soporte a Producción PAE"),
                    ("ALUVION", "Soporte a Producción Aluvión-Vista"),
                    ("CERCOS", "Cercos Perimetrales y Corralitos"),
                    ("METAL", "Metalúrgica"),
                    ("GENERAL", "GENERAL (a prorratear por ventas)"),
                    (
                        "PERSONAL",
                        "GENERAL (a prorratear por personal afectado) — ej. EPP",
                    ),
                    ("NA", "N/A — Otros Egresos (no aplica)"),
                ],
                help_text='Si la factura es de varios servicios, elegí "GENERAL (a prorratear por ventas)". Si es de EPP (mamelucos, calzado, etc.), elegí "GENERAL (a prorratear por personal afectado)": se reparte según la cantidad de personal de cada servicio en el mes.',
                max_length=20,
                verbose_name="servicio asignado",
            ),
        ),
    ]
