# Generated by Django 5.2.17 on 2026-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_neto_e_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("MATERIALES", "Materiales e Insumos"),
                    ("COMBUSTIBLE", "Combustible"),
                    ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                    ("OTROS_DIRECTOS", "Otros Costos Directos"),
                    (
                        "OTROS_EGRESOS",
                        "Otros Egresos (no corresponde a Costos por Servicio)",
                    ),
                    (
                        "GO_SERVICIOS",
                        "Gasto Operativo — Servicios (luz, gas, agua, teléfono, internet, alarma)",
                    ),
                    ("GO_SEGUROS", "Gasto Operativo — Seguros"),
                    ("GO_ALQUILERES", "Gasto Operativo — Alquileres"),
                    ("GO_IMPUESTOS", "Gasto Operativo — Impuestos y Tasas"),
                ],
                max_length=20,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("MATERIALES", "Materiales e Insumos"),
                    ("COMBUSTIBLE", "Combustible"),
                    ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                    ("OTROS_DIRECTOS", "Otros Costos Directos"),
                    (
                        "OTROS_EGRESOS",
                        "Otros Egresos (no corresponde a Costos por Servicio)",
                    ),
                    (
                        "GO_SERVICIOS",
                        "Gasto Operativo — Servicios (luz, gas, agua, teléfono, internet, alarma)",
                    ),
                    ("GO_SEGUROS", "Gasto Operativo — Seguros"),
                    ("GO_ALQUILERES", "Gasto Operativo — Alquileres"),
                    ("GO_IMPUESTOS", "Gasto Operativo — Impuestos y Tasas"),
                ],
                max_length=20,
                verbose_name="categoría",
            ),
        ),
    ]
