# Generated by Django 5.2.17 on 2026-09-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_compra_repartida_por_servicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidacionnomina",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Criterio de caja: el mes en que se PAGA. Ej.: los sueldos del período Junio, que se pagan en Julio, van en Julio; las contribuciones (F.931) y los sindicatos del período Junio también.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="gestion.periodo",
                verbose_name="mes de pago",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionnomina",
            name="periodo",
            field=models.ForeignKey(
                help_text="Criterio de caja: el mes en que se PAGA. Ej.: los sueldos del período Junio, que se pagan en Julio, van en Julio; las contribuciones (F.931) y los sindicatos del período Junio también.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nomina",
                to="gestion.periodo",
                verbose_name="mes de pago",
            ),
        ),
    ]
