# Generated by Django 5.2.17 on 2026-09-30 17:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_nomina_mes_de_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionnomina",
            name="haberes_pagados_en_el_mes",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Sólo para quienes cobran por quincena (UOCRA): el importe bruto de la 1ª quincena, que se paga dentro del mismo mes. El resto de los haberes, las contribuciones (F.931) y los sindicatos del período se pagan el mes siguiente. Para el personal mensual dejalo en 0.",
                max_digits=16,
                verbose_name="haberes pagados dentro del mismo mes",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionnomina",
            name="haberes_pagados_en_el_mes",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Sólo para quienes cobran por quincena (UOCRA): el importe bruto de la 1ª quincena, que se paga dentro del mismo mes. El resto de los haberes, las contribuciones (F.931) y los sindicatos del período se pagan el mes siguiente. Para el personal mensual dejalo en 0.",
                max_digits=16,
                verbose_name="haberes pagados dentro del mismo mes",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionnomina",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="El período liquidado (devengado), aunque se pague el mes siguiente. Ej.: los sueldos, el F.931 y los sindicatos del período Junio van en Junio. El reporte de Flujo de fondos los ubica en el mes de pago.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="gestion.periodo",
                verbose_name="período (mes trabajado)",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionnomina",
            name="periodo",
            field=models.ForeignKey(
                help_text="El período liquidado (devengado), aunque se pague el mes siguiente. Ej.: los sueldos, el F.931 y los sindicatos del período Junio van en Junio. El reporte de Flujo de fondos los ubica en el mes de pago.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nomina",
                to="gestion.periodo",
                verbose_name="período (mes trabajado)",
            ),
        ),
    ]
