# Generated by Django 5.2.17 on 2026-09-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_nomina_devengado_y_pagos"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperiodo",
            name="solo_flujo",
            field=models.BooleanField(
                default=False,
                help_text="Marcar en los meses anteriores al inicio del seguimiento que se cargan sólo porque sus sueldos, F.931 y sindicatos se pagan en el mes siguiente. No aparecen en los reportes de resultados.",
                verbose_name="sólo para el flujo de fondos",
            ),
        ),
        migrations.AddField(
            model_name="periodo",
            name="solo_flujo",
            field=models.BooleanField(
                default=False,
                help_text="Marcar en los meses anteriores al inicio del seguimiento que se cargan sólo porque sus sueldos, F.931 y sindicatos se pagan en el mes siguiente. No aparecen en los reportes de resultados.",
                verbose_name="sólo para el flujo de fondos",
            ),
        ),
    ]
