# Generated by Django 5.2.17 on 2026-10-07 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_periodo_solo_flujo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionnomina",
            name="pagos_transferencia",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Lo que se paga aparte del recibo y de la factura, por transferencia. Se toma como pagado el mes siguiente, junto con los sueldos del período.",
                max_digits=16,
                verbose_name="pagos por transferencia (fuera de recibo)",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionnomina",
            name="pagos_transferencia",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Lo que se paga aparte del recibo y de la factura, por transferencia. Se toma como pagado el mes siguiente, junto con los sueldos del período.",
                max_digits=16,
                verbose_name="pagos por transferencia (fuera de recibo)",
            ),
        ),
    ]
