# Generated by Django 5.2.17 on 2026-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0010_pagos_transferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="tipo_costo",
            field=models.CharField(
                choices=[
                    (
                        "VARIABLE",
                        "Costo variable (depende de lo que se trabaja/factura)",
                    ),
                    ("FIJO", "Costo fijo (se paga todos los meses, se facture o no)"),
                ],
                default="VARIABLE",
                help_text="Sólo para Materiales, Combustible, Mantenimiento y Otros Costos Directos. Costo fijo: se paga todos los meses aunque no se facture (ej. alquiler de trailers o vehículos). Si se asigna a un servicio, se le carga a ese servicio; si es GENERAL, se reparte como el resto de los costos fijos. En el Punto de Equilibrio cuenta como costo fijo.",
                max_length=10,
                verbose_name="tipo de costo",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompra",
            name="tipo_costo",
            field=models.CharField(
                choices=[
                    (
                        "VARIABLE",
                        "Costo variable (depende de lo que se trabaja/factura)",
                    ),
                    ("FIJO", "Costo fijo (se paga todos los meses, se facture o no)"),
                ],
                default="VARIABLE",
                help_text="Sólo para Materiales, Combustible, Mantenimiento y Otros Costos Directos. Costo fijo: se paga todos los meses aunque no se facture (ej. alquiler de trailers o vehículos). Si se asigna a un servicio, se le carga a ese servicio; si es GENERAL, se reparte como el resto de los costos fijos. En el Punto de Equilibrio cuenta como costo fijo.",
                max_length=10,
                verbose_name="tipo de costo",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("MATERIALES", "Materiales e Insumos"),
                    ("COMBUSTIBLE", "Combustible"),
                    ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                    ("OTROS_DIRECTOS", "Otros Costos Directos"),
                    (
                        "OTROS_EGRESOS",
                        "Otros Egresos (no corresponde a Costos por Servicio)",
                    ),
                    (
                        "GO_SERVICIOS",
                        "Gasto Operativo — Servicios (luz, gas, agua, teléfono, internet, alarma)",
                    ),
                    ("GO_SEGUROS", "Gasto Operativo — Seguros"),
                    ("GO_ALQUILERES", "Gasto Operativo — Alquileres"),
                    ("GO_IMPUESTOS", "Gasto Operativo — Impuestos y Tasas"),
                    (
                        "GASTO_BANCARIO",
                        "Gasto Bancario (comisiones facturadas por el banco)",
                    ),
                ],
                max_length=20,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="gastomanual",
            name="rubro",
            field=models.CharField(
                choices=[
                    ("ALQUILERES", "Alquileres"),
                    ("SERVICIOS", "Servicios (luz, gas, internet, etc.)"),
                    ("SEGUROS", "Seguros"),
                    ("IMPUESTOS", "Impuestos y Tasas"),
                    ("OTROS_GO", "Otros Gastos Operativos"),
                    (
                        "FIJOS_OPERACION",
                        "Costos Fijos de Operación (compras de costo fijo)",
                    ),
                    ("LEASING", "Leasing Vehículos/Equipos"),
                    ("PLANES_PAGO", "Cuotas Planes de Pago"),
                    ("COMISIONES", "Comisiones Bancarias"),
                    ("INTERESES", "Intereses por Financiación"),
                    ("LEY_25413", "Impuesto a los Créditos y Débitos (Ley 25.413)"),
                    ("OTROS_INGRESOS", "Otros Ingresos"),
                    ("OTROS_EGRESOS_NO", "Otros Egresos (no operativos)"),
                    ("GANANCIAS", "Impuesto a las Ganancias (estimado)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("MATERIALES", "Materiales e Insumos"),
                    ("COMBUSTIBLE", "Combustible"),
                    ("MANT_EQUIPOS", "Mantenimiento de Equipos"),
                    ("OTROS_DIRECTOS", "Otros Costos Directos"),
                    (
                        "OTROS_EGRESOS",
                        "Otros Egresos (no corresponde a Costos por Servicio)",
                    ),
                    (
                        "GO_SERVICIOS",
                        "Gasto Operativo — Servicios (luz, gas, agua, teléfono, internet, alarma)",
                    ),
                    ("GO_SEGUROS", "Gasto Operativo — Seguros"),
                    ("GO_ALQUILERES", "Gasto Operativo — Alquileres"),
                    ("GO_IMPUESTOS", "Gasto Operativo — Impuestos y Tasas"),
                    (
                        "GASTO_BANCARIO",
                        "Gasto Bancario (comisiones facturadas por el banco)",
                    ),
                ],
                max_length=20,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgastomanual",
            name="rubro",
            field=models.CharField(
                choices=[
                    ("ALQUILERES", "Alquileres"),
                    ("SERVICIOS", "Servicios (luz, gas, internet, etc.)"),
                    ("SEGUROS", "Seguros"),
                    ("IMPUESTOS", "Impuestos y Tasas"),
                    ("OTROS_GO", "Otros Gastos Operativos"),
                    (
                        "FIJOS_OPERACION",
                        "Costos Fijos de Operación (compras de costo fijo)",
                    ),
                    ("LEASING", "Leasing Vehículos/Equipos"),
                    ("PLANES_PAGO", "Cuotas Planes de Pago"),
                    ("COMISIONES", "Comisiones Bancarias"),
                    ("INTERESES", "Intereses por Financiación"),
                    ("LEY_25413", "Impuesto a los Créditos y Débitos (Ley 25.413)"),
                    ("OTROS_INGRESOS", "Otros Ingresos"),
                    ("OTROS_EGRESOS_NO", "Otros Egresos (no operativos)"),
                    ("GANANCIAS", "Impuesto a las Ganancias (estimado)"),
                ],
                max_length=20,
            ),
        ),
    ]
