# Generated by Django 5.2.17 on 2026-10-09 18:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_compras_costo_fijo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionnomina",
            name="beneficios_adicionales",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Pagos que hace la empresa a cuenta de la persona (ej. cuotas de sus planes de ARCA debitadas de la cuenta de la empresa). Suman al costo del período y se toman como pagados en el mismo mes.",
                max_digits=16,
                verbose_name="beneficios adicionales",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionnomina",
            name="beneficios_adicionales",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Pagos que hace la empresa a cuenta de la persona (ej. cuotas de sus planes de ARCA debitadas de la cuenta de la empresa). Suman al costo del período y se toman como pagados en el mismo mes.",
                max_digits=16,
                verbose_name="beneficios adicionales",
            ),
        ),
    ]
